### PR TITLE
Fixed wrong "this" reference

### PR DESCRIPTION
**Pull request by fredluetkemeier**

### CODE REVIEW

**Comment by TarekRaafat** [comment]
@fredluetkemeier thanks for your prompt response, I would highly appreciate if you could share use case example for the new feature.

**Comment by fredluetkemeier** [comment]
> @fredluetkemeier thanks for your prompt response, I would highly appreciate if you could share use case example for the new feature.

Would you prefer me to take a screenshot or update the documentation myself with a pull request? Thanks!

**Comment by TarekRaafat** [comment]
Screenshot or copy of the code would be perfect and I'll take care of updating the docs.

Thanks!

**Comment by fredluetkemeier** [comment]
I apologize for the delay on this. I have attached a .zip file with an example project's source code inside. It contains my implementation for custom suggestion navigation. If you run into any issues or something doesn't work as expected, please let me know.

Additionally, feel free to use a completely different example if you think this one is too long or could be done a different way. 

[navigation-example.zip](https://github.com/TarekRaafat/autoComplete.js/files/3536100/navigation-example.zip)

Have a great day.

**Comment by TarekRaafat** [comment]
@fredluetkemeier thank you so much, I appreciate your time and effort.

You too have a great day, cheers! :)

**Pull request merged**
