### PR TITLE
add polyfill functions for IE11: CustomEvent, Element.prototype.closest

### PR DESCRIPTION
**Pull request by g-viet**
Relates to this issue: https://github.com/TarekRaafat/autoComplete.js/issues/43

Todo list:
- [x] Use `CustomEventWrapper` instead of default `window.CustomEvent`
- [x] Init `Element.prototype.Closest` if not exists

### CODE REVIEW

**Comment by g-viet** [comment]
@TarekRaafat Could you please verify this PR ?

**Comment by TarekRaafat** [comment]
Thanks @g-viet! :)

**Comment by g-viet** [comment]
Many thanks @TarekRaafat !
You saved me 😄 
Could you please tell me when will you release this PR?

**Comment by TarekRaafat** [comment]
Thanks to you @g-viet and your valuable contribution!

Hopefully this weekend, because I'll have to go through the entire code and double check everything is alright and optimized as much as possible before releasing it and I might need to decrease the library size as well a little bit since the last enhancement increased it.

Plus, I need to enhance the `eventEmitter` behavior in the next release as well to be fired on empty input field after clearing the entire query not just on typing.

Cheers! :)

**Comment by g-viet** [comment]
Sure ! Thank you for the confirmation 👌

**Comment by g-viet** [comment]
Hi @TarekRaafat ,
Sorry for annoying many times.
I just want to confirm when this PR will be released.
Hope enhancing `eventEmitter` to be OK now 💪

**Comment by TarekRaafat** [comment]
Hello @g-viet,

My apologies for the delay.
Not a problem, never hesitate to ask.
The new release `v6.0.0` is coming out surely this Friday, and i'll make sure to let you know as soon as it's out.
Thanks for checking, It's going in the right direction.

Have a good day! :)

**Comment by g-viet** [comment]
@TarekRaafat Never mind. Thank you so much 💪

**Comment by TarekRaafat** [comment]
Hello @g-viet ,

Check out the new release [v6.0.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v6.0.0), [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js) & [CDN](https://www.jsdelivr.com/package/npm/@tarekraafat/autocomplete.js)

Let me know your thoughts.

Have a good day, cheers! :)

**Comment by g-viet** [comment]
@TarekRaafat That's great !
Thank you so much.
I'm done the task at job 😁

**Pull request merged**
