### PR TITLE
Support data source reload

### PR DESCRIPTION
**Pull request by Brostafa**
First of all I should start by saying that you've built an amazing library!

This PR should resolve https://github.com/TarekRaafat/autoComplete.js/issues/19 and https://github.com/TarekRaafat/autoComplete.js/issues/36

I've added `shouldCacheSrc` property to the class which defaults to `true`. However, when it's set to `false` it will call `data.src()` function on every keyup event and the returned value of `data.src()` will update the value of `dataSrc`

AJAX example:

```
new autoComplete({
  // ... other properties
  data: {
    src: async () => {
       const userInput = document.querySelector('#cityInput').value
       const response = await fetch(`/get-cities?name=${userInput}`)
       const cities = await response.json()
      // ... other code
      return cities
    }
  },
  shouldCacheSrc: false // important to invoke data.src() on every keyup
  // ... other properties
})
```

### CODE REVIEW

**Comment by TarekRaafat** [comment]
@Brostafa thank you so much, i'm glad you like it! :)

I highly appreciate the time and effort you've invested to come up with this clean and tidy solution.

I just would like to rename the `shouldCacheSrc` property to be more descriptive if you don't mind, and I would like to hear your suggestions on it.

Cheers! :)

**Comment by Brostafa** [comment]
>I just would like to rename the shouldCacheSrc property to be more descriptive if you don't mind, and I would like to hear your suggestions on it.

Please, feel free to change it to whatever you want. Nothing comes to my mind in terms of a different good name, maybe `cacheDataSource` or `recreateDataSource`?

**Comment by shaikemarc** [comment]
@TarekRaafat Amazing lib, @Brostafa thanks for that useful PR.
When do you think you will publish that fix to npm? 
That is exactly the feature i need as my case is: no data is downloaded to the client until the user searches..

10x!

**Comment by TarekRaafat** [comment]
@shaikemarc thank you so much, i'm glad you like it!

The release is rolling out in couple of days within this week to CDN and NPM as well, carries couple of new handy features including @Brostafa's great enhancement, stay tuned.

Cheers! :)

**Comment by aviatrix** [comment]
@Brostafa, thank you for this PR. It makes the library quite a bit more awesome!

**Pull request merged**
