### PR TITLE
Wrap search logic in a promise to handle a large set of data

### PR DESCRIPTION
**Pull request by Johann-S**
It works perfectly without freezing the main UI.

BTW Opera Mini doesn't support Promise, is it a real problem ?

Fixes: #28

### CODE REVIEW

**Comment by PuKoren** [comment]
@TarekRaafat , what do you think about this ?

**Comment by Postlagerkarte** [comment]
+1 on this PR

**Comment by TarekRaafat** [comment]
@Johann-S thank you so much for your support!

Don't worry about `Opera Mini` support, I will check polyfilling the promise.

Cheers! :)

**Comment by Johann-S** [comment]
Happy to help you 👍

**Pull request merged**
