### PR TITLE
Custom selected item and highlighted text classes

### PR DESCRIPTION
**Pull request by jerrykan**
Allow users better control over how the selected item and highlighted text is displayed by letting them use their own custom classes instead of the ones hard-coded in the source code.

### CODE REVIEW

**Comment by jerrykan** [comment]
An example use-case of this is being able to use the default bootstrap classes without needing to include the autoComplete CSS or define separate `autoComplete_selected` and `autoComplete_highlighted` classes. ie:

```
var ac = new autoComplete({
  ...
  highlight: true,
  highlightedClass: "fw-bolder",
  selectedClass: "bg-light",
  resultsList: {
    className: "dropdown-menu show",
  },
  resultItem: {
    className: "dropdown-item",
  },
})
```

**Comment by TarekRaafat** [comment]
Hello @jerrykan,

Thanks man for this PR I love it actually.

But we need to take a collective decision on which direction for implementing those new APIs would make more sense:

1- Feature grouping:
```js
highlight: {
    render: true,
    className: "fw-bolder",
},
resultsList: {
    render: true,
    container: (source) => {},
    className: "bg-light",
},
selection: {
    className: "bg-light",
},
```

2- Topic grouping:
```js
highlight: true,
resultsList: {
    render: true,
    container: (source) => {},
}
classes: {
    highlighted: "fw-bolder",
    selected: "bg-light",
    resultsList: "dropdown-menu show",
    reslutItem: "dropdown-item",
},
```

3- You're most welcome if you have more ideas..
```js
}
    ?
}
```

Noting that the second approach would incur a complete redesign for the API configurations. (I'm totally okay with that if it's broken already)

Let me know your thoughts.


Cheers, and have a nice day! :)

**Comment by jerrykan** [comment]
Hello @TarekRaafat personally I think the feature grouping option is the one that seems the most intuitive.

**Comment by TarekRaafat** [comment]
@jerrykan, I agree with you.
Would you update your PR accordingly or shall I take care of it?

**Comment by jerrykan** [comment]
@TarekRaafat I've pushed a commit with the suggested changes. Unfortunately I couldn't find a nice way to provide backwards compatibility for the use of the `hightlight` value (I don't have much experience with javascript). I'm not sure how much you care about backwards compatibility.

You may also want to check the formatting of the changes I made to the `docs/README.md`

**Comment by elioncho** [comment]
> An example use-case of this is being able to use the default bootstrap classes without needing to include the autoComplete CSS or define separate `autoComplete_selected` and `autoComplete_highlighted` classes. ie:
> 
> ```
> var ac = new autoComplete({
>   ...
>   highlight: true,
>   highlightedClass: "fw-bolder",
>   selectedClass: "bg-light",
>   resultsList: {
>     className: "dropdown-menu show",
>   },
>   resultItem: {
>     className: "dropdown-item",
>   },
> })
> ```

Do you have an example of full integration with Bootstrap 5 or 4?

**Comment by TarekRaafat** [comment]
Hello @elioncho,

Here is a simple `Bootstrap 5` styling [example](https://codepen.io/tarekraafat/pen/VwPJxmx?editors=0010) that I've prepared for you.

I hope this answers your question, please let me know if it does not.

Have a nice day! :)

**Comment by elioncho** [comment]
> Hello @elioncho,
> 
> Here is a simple `Bootstrap 5` styling [example](https://codepen.io/tarekraafat/pen/VwPJxmx?editors=0010) that I've prepared for you.
> 
> I hope this answers your question, please let me know if it does not.
> 
> Have a nice day! :)

Thanks for the example, I am already implementing it. I have a question about it:

Once the dropdown is shown, the content below it is pushed down (happens to me too). I see that is not the case in this other demo you have shared before https://tarekraafat.github.io/autoComplete.js/demo/ Why is the content pushed down in the bootstrap 5 demo?

**Pull request merged**
